#!/usr/bin/env ruby
require 'logger'
require 'tempfile'
require "#{File.join(__dir__, 'upload_template')}"
require 'json'

require 'pry'

log = Logger.new("/tmp/packer-upload-#{(0...8).map { (65 + rand(26)).chr }.join}")
log.level = Logger::INFO

FILE=ARGV[0]

# Abiquo info
api_url = ENV['ABIQUO_API_URL']
abiuser = ENV['ABIQUO_USERNAME']
abipass = ENV['ABIQUO_PASSWORD']
abidc   = ENV['DATACENTER']

unless FILE.end_with? 'vmdk'
  log.info "Skipping non VMDK file #{FILE}."
  exit 0
end

tpl_vars = JSON.parse(ENV['TEMPLATE'])
tpl_vars.merge!({ 
  "abiquo_api_url" => api_url,
  "abiquo_username" => abiuser,
  "abiquo_password" => abipass,
  "abiquo_datacenter" => abidc,
  "file" => FILE,
  'logger' => log
})
tpl_vars['icon_url'] = ENV['ICON_URL'] if ENV['ICON_URL']

uploader = Abiquo::Packer::TemplateUploader.new(tpl_vars)
abq_template = uploader.upload
log.info "Uploaded template #{abq_template.name}."
